#!/bin/bash

set -eo pipefail
source common.sh

start

metadata_short_sha=$(echo "${K8S_METADATA_UID}" | sha1sum | cut -c -7)
table_name="${metadata_short_sha}.${K8S_METADATA_NAMESPACE}.${K8S_METADATA_NAME}"

aws dynamodb delete-table --table-name "${table_name}" >&2

end

