---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: microdc-dynamodb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microdc-dynamodb-operator
subjects:
  - kind: ServiceAccount
    name: microdc-dynamodb-operator
    namespace: microdc
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: microdc-dynamodb-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - aws.microdc.io
    resources:
      - dynamodbs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microdc-dynamodb-operator
  namespace: microdc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microdc-dynamodb-operator
  namespace: microdc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microdc-dynamodb-operator
      annotations:
        iam.amazonaws.com/role: microdc-dynamodb-operator
    spec:
      serviceAccountName: microdc-dynamodb-operator
      containers:
        - name: operator
          image: 982704890815.dkr.ecr.ap-southeast-2.amazonaws.com/dynamodb-controller:latest
          env:
            - name: AWS_DEFAULT_REGION
              value: ap-southeast-2
            - name: DEBUG
              value: yo
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 50m
